# File: main.yaml
# Project: Elektrobit-Demo-Software-Recipes
# Created Date: Th/05/2025
# -----
# Last Modified: Th/05/2025 15:14:28
# -----
# Copyright (c) 2025 GlobalLogic, a Hitachi Group Company

license_key: <license_key>
